fix(ci): initialize all Terraform configurations

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -49,7 +49,7 @@ jobs:
             }}
 
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v5
+        uses: aws-actions/configure-aws-credentials@v6
         with:
           role-to-assume: ${{ vars.AWS_DEPLOYMENT_ROLE_ARN }}
           aws-region: ${{ vars.AWS_REGION }}
@@ -61,7 +61,7 @@ jobs:
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v4
         with:
-          terraform_version: "1.14.6"
+          terraform_version: "1.15.8"
           terraform_wrapper: false
 
       - name: Initialize Terraform
@@ -97,35 +97,35 @@ jobs:
             -no-color \
             deployment.tfplan
 
-      # - name: Apply deployment plan
-        # working-directory: infrastructure/terraform
-        # run: |
-        #  terraform apply \
-        #    -input=false \
-        #    -auto-approve \
-        #    deployment.tfplan
+    #   - name: Apply deployment plan
+    #     working-directory: infrastructure/terraform
+    #     run: |
+    #      terraform apply \
+    #        -input=false \
+    #        -auto-approve \
+    #        deployment.tfplan
 
-      - name: Verify infrastructure convergence
-        working-directory: infrastructure/terraform
-        run: |
-            set +e
+    #   - name: Verify infrastructure convergence
+    #     working-directory: infrastructure/terraform
+    #     run: |
+    #       set +e
 
-            terraform plan \
-            -input=false \
-            -detailed-exitcode \
-            -no-color
+    #       terraform plan \
+    #         -input=false \
+    #         -detailed-exitcode \
+    #         -no-color
 
-            exit_code=$?
+    #       exit_code=$?
 
-            if [ "$exit_code" -eq 0 ]; then
-            echo "Infrastructure matches the Terraform configuration."
-            exit 0
-            fi
+    #       if [ "$exit_code" -eq 0 ]; then
+    #         echo "Infrastructure matches the Terraform configuration."
+    #         exit 0
+    #       fi
 
-            if [ "$exit_code" -eq 2 ]; then
-            echo "Terraform detected changes immediately after deployment."
-            exit 1
-            fi
+    #       if [ "$exit_code" -eq 2 ]; then
+    #         echo "Terraform detected changes immediately after deployment."
+    #         exit 1
+    #       fi
 
-            echo "Terraform plan failed."
-            exit 1
+    #       echo "Terraform plan failed."
+    #       exit 1
